import "@testing-library/jest-dom/vitest";
import { afterAll, afterEach, beforeAll, vi } from "vitest";
import { cleanup } from "@testing-library/react";
import { setupServer } from "msw/node";
import { handlers, resetProjects } from "../mocks/handlers";
export const server = setupServer(...handlers);
window.scrollTo = vi.fn();
beforeAll(() => server.listen({ onUnhandledRequest: "error" }));
afterEach(() => { cleanup(); server.resetHandlers(); resetProjects(); });
afterAll(() => server.close());
